export const GET_FLIGHTS = "GET_FLIGHTS";
export const FIND_AIRPLANES = "FIND_AIRPLANES";
export const FIND_LANES = "FIND_LANES";
export const CREATE_USER = "CREATE_USER";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTHENTICATED = "AUTHENTICATED_USER";
export const UNAUTHENTICATED = "UNAUTHENTICATED_USER";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR_USER";