export const GET_FLIGHTS = "GET_FLIGHTS";
export const GET_CURRENT_FLIGHT = "GET_CURRENT_FLIGHT";
export const FLIGHT_NOT_FOUND = "FLIGHT_NOT_FOUND";
export const SEARCH_FLIGHTS = "SEARCH_FLIGHTS";
export const FIND_AIRPLANES = "FIND_AIRPLANES";
export const FIND_LANES = "FIND_LANES";
export const CREATE_USER = "CREATE_USER";